[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_escrow = "A2AuQQSg3k5hXJNnXNBCz4rxTep33LzmuNdmPzVUiQwd"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
